# Generated by Django 5.2.16 on 2026-07-14 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('mandate', models.TextField(blank=True)),
                ('sectors', models.JSONField(default=list)),
                ('stages', models.JSONField(default=list)),
                ('check_size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('check_size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('portfolio_count', models.PositiveIntegerField(default=0)),
                ('website_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecosystem_investor',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expertise_areas', models.JSONField(default=list)),
                ('current_role', models.CharField(blank=True, max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_hours_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecosystem_mentor',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startup_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('pitch_summary', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('problem_statement', models.TextField(blank=True)),
                ('solution_summary', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('early_revenue', 'Early Revenue'), ('growth', 'Growth')], default='idea', max_length=20)),
                ('trl', models.PositiveIntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True)),
                ('deck_url', models.URLField(blank=True)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecosystem_startup',
                'ordering': ['-created_at'],
            },
        ),
    ]
