# Generated by Django 5.2.16 on 2026-07-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_add_embedding_fields_and_ivfflat_indexes'),
        ('ecosystem', '0002_add_startup_filter_indexes'),
    ]

    operations = [
    ]
