# Generated by Django 5.2.16 on 2026-08-01 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
        ('ecosystem', '0003_merge_20260726_2114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('competition', 'Competition'), ('patent', 'Patent'), ('publication', 'Publication'), ('tech_transfer', 'Tech Transfer'), ('leadership', 'Leadership'), ('project', 'Project'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('award', 'Award')], default='competition', max_length=30)),
                ('title', models.CharField(max_length=240)),
                ('rank_or_prize', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('certificate_path', models.CharField(blank=True, max_length=512)),
                ('ner_confidence', models.FloatField(blank=True, null=True)),
                ('topic_tags', models.JSONField(default=list)),
                ('nirf_countable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecosystem_achievement',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('organiser', models.CharField(blank=True, max_length=150)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('nirf_recognised', models.BooleanField(default=False)),
                ('eligible_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecosystem_competition',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mentorship', 'Mentorship'), ('funding_match', 'Funding Match'), ('club_membership', 'Club Membership'), ('competition_team', 'Competition Team'), ('mou', 'MoU')], max_length=30)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('success_label', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecosystem_interaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='startup',
            name='ecosystem_startup_funding_stage_btree_idx',
        ),
        migrations.RenameIndex(
            model_name='startup',
            new_name='startup_sector_idx',
            old_name='ecosystem_startup_sector_btree_idx',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='funding_stage',
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['stage'], name='startup_stage_idx'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='ecosystem.startup'),
        ),
        migrations.AddField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='ecosystem.competition'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ecosystem.startup'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
