# Generated by Django 5.2.16 on 2026-08-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_achievement_impact_score_and_more'),
        ('ecosystem', '0004_achievement_competition_interaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_initiated', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to='accounts.profile'),
        ),
    ]
