# Generated by Django 5.2.16 on 2026-08-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_filter_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='prof_dept_idx',
            old_name='accounts_profile_department_btree_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_role_idx',
            old_name='auth_user_role_btree_idx',
        ),
    ]
