# Generated by Django 5.2.16 on 2026-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievement_impact_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='at_risk_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='grit_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completion_pct',
            field=models.FloatField(default=0.0),
        ),
    ]
